@startjson get-comments-by-post-id
{
  "path": "/comments/:postId",
  "httpMethod": "GET",
  "header": {
    "authorization": "string"
  }
  ,
  "param": {
    "postId": "number"
  }
  ,
  "query": {
    "limit": "number",
    "offset": "number"
  }
  ,
  "response": {
    "successful": "boolean",
    "errorCode": "string",
    "message": "string",
    "data":
    {
      "items": [{
        "id": "number",
        "content": "string",
        "createdAt": "string",
        "createdBy": "datetime(6)",
        "postId": "number",
        "updatedAt": "string",
        "updatedBy": "datetime(6)",
        "userId": "number",
        "username": "string",
        "userImageUrl": "string"
      }
      ],
      "totalItems": "number"
    }
  }
  ,
  "errorCode": [
  {
    "code": "00",
    "message": "Success",
    "httpStatus": "200"
  }
  ,
  {
    "code": "03",
    "message": "Server Error",
    "httpStatus": "500"
  }
  ,
  {
    "code": "06",
    "message": "Invalid data",
    "httpStatus": "400"
  }
  ,
  {
    "code": "10",
    "message": "Unauthorized",
    "httpStatus": "401"
  }
  ]
}
@endjson